import React from 'react';
import { Language } from '../App';
import { BotIcon } from './icons';
import { motion } from 'framer-motion';

interface AboutPageProps {
  language: Language;
}

const AboutPage: React.FC<AboutPageProps> = ({ language }) => {
  const getText = () => {
    if (language === 'sw') {
        return {
            title: "Kuhusu Schisto-Care",
            missionTitle: "Dhamira Yetu",
            missionDesc: "Schisto-Care imejitolea kuziba pengo la habari kuhusu Kichocho (Bilharzia). Lengo letu ni kutoa mwongozo unaofikiwa kwa urahisi, sahihi, na wa haraka kwa watu walio katika maeneo yaliyoathirika, tukitumia nguvu ya akili bandia kuelimisha, kusaidia katika dalili za utambuzi wa mapema, na kukuza hatua za kuzuia.",
            aiTitle: "Uchambuzi wa AI",
            aiDesc: "Ikiendeshwa na mifano ya Gemini ya Google, msaidizi huchakata maulizo yako ya maandishi na sauti ili kutoa habari za matibabu zinazozingatia muktadha.",
            multiTitle: "Usaidizi wa Njia Mbalimbali",
            multiDesc: "Pakia ripoti za matibabu au picha, ongea kwa kawaida, au piga gumzo kupitia maandishi. Mfumo umeundwa kukuelewa vyovyote unavyowasiliana.",
            disclaimerTitle: "Kanusho la Matibabu",
            disclaimerDesc: "Msaidizi wa Schisto-Care ni chombo cha habari na HATOI utambuzi rasmi wa kimatibabu. Habari inayozalishwa na AI haipaswi kuchukua nafasi ya ushauri wa kitaalamu wa matibabu. Wasiliana na mtoa huduma ya afya aliyehitimu kila wakati kwa vipimo, utambuzi, na matibabu."
        };
    } else if (language === 'luo') {
        return {
            title: "E Wi Schisto-Care",
            missionTitle: "Gima Watiyo",
            missionDesc: "Schisto-Care ochiwore konyo ji e weche mag Kichocho (Bilharzia). Gima wamanyo en chiwo puonj maber, kendo mayot, ne ji manie aluora ma tuo ni nitie. Watiyo gi lony mar AI mondo wapuonj, wafweny ranyisi mag tuo, kendo wageng'e.",
            aiTitle: "Lony mar AI",
            aiDesc: "Watiyo gi Google Gemini AI kuom nono penjo magi, bed ni iwuoyo kata indikogo, mondo wachiw kony.",
            multiTitle: "Yore Mathoth mag Konyruok",
            multiDesc: "Or picha kata ndiko, wuo e dwol mari, kata ndik message. Program-ni olos mondo owinji e yo moro amora.",
            disclaimerTitle: "Ote Maduong",
            disclaimerDesc: "Schisto-Care en mar chiwo nge'yo kende, to OK en Daktari. Weche ma AI chiwo ok nyal kar layo daktari. Kinde duto, dhi e ospital mondo opimi kendo othiethi."
        };
    }
    return {
        title: "About Schisto-Care",
        missionTitle: "Our Mission",
        missionDesc: "Schisto-Care is dedicated to bridging the information gap regarding Schistosomiasis (Bilharzia). Our goal is to provide accessible, accurate, and immediate guidance to individuals in affected regions, utilizing the power of artificial intelligence to educate, assist in early detection signs, and promote preventative measures.",
        aiTitle: "AI Analysis",
        aiDesc: "Powered by Google's Gemini models, the assistant processes your text and voice queries to provide context-aware medical information.",
        multiTitle: "Multimodal Support",
        multiDesc: "Upload medical reports or images, speak naturally, or chat via text. The system is designed to understand you however you communicate.",
        disclaimerTitle: "Medical Disclaimer",
        disclaimerDesc: "The Schisto-Care Assistant is an informational tool and does NOT provide official medical diagnoses. The information generated by AI should not replace professional medical advice. Always consult with a qualified healthcare provider for testing, diagnosis, and treatment."
    };
  };

  const t = getText();

  return (
    <motion.div 
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        className="flex flex-col h-full overflow-y-auto bg-[#F8FAFC] text-gray-800 p-6 md:p-12"
    >
        <div className="max-w-4xl mx-auto w-full">
            {/* Header */}
            <div className="text-center mb-12">
                <motion.div 
                    initial={{ scale: 0 }}
                    animate={{ scale: 1 }}
                    transition={{ type: "spring", stiffness: 100 }}
                    className="inline-block p-6 rounded-3xl bg-white mb-6 shadow-xl shadow-blue-100"
                >
                    <BotIcon className="w-16 h-16 text-blue-600" />
                </motion.div>
                <motion.h1 
                    initial={{ y: 20, opacity: 0 }}
                    animate={{ y: 0, opacity: 1 }}
                    transition={{ delay: 0.2 }}
                    className="text-3xl md:text-5xl font-bold text-gray-900 mb-4 tracking-tight"
                >
                    {t.title}
                </motion.h1>
                <div className="h-1.5 w-24 bg-blue-500 mx-auto rounded-full opacity-20"></div>
            </div>

            {/* Mission Section */}
            <motion.div 
                initial={{ y: 30, opacity: 0 }}
                animate={{ y: 0, opacity: 1 }}
                transition={{ delay: 0.3 }}
                className="bg-white rounded-3xl p-8 shadow-[0_10px_40px_-10px_rgba(0,0,0,0.05)] mb-8 border border-gray-50"
            >
                <h2 className="text-2xl font-bold text-blue-600 mb-4">
                    {t.missionTitle}
                </h2>
                <p className="text-gray-600 leading-relaxed text-lg">
                    {t.missionDesc}
                </p>
            </motion.div>

            {/* How it Works Grid */}
            <div className="grid md:grid-cols-2 gap-8 mb-12">
                <motion.div 
                    initial={{ x: -20, opacity: 0 }}
                    animate={{ x: 0, opacity: 1 }}
                    transition={{ delay: 0.4 }}
                    className="bg-white rounded-2xl p-8 shadow-sm hover:shadow-lg transition-shadow border border-gray-100"
                >
                     <h3 className="text-xl font-bold text-gray-800 mb-3 flex items-center gap-3">
                        <span className="bg-blue-100 text-blue-700 py-1 px-3 rounded-lg text-sm font-bold">01</span>
                        {t.aiTitle}
                     </h3>
                     <p className="text-gray-500 leading-relaxed">
                        {t.aiDesc}
                     </p>
                </motion.div>
                <motion.div 
                    initial={{ x: 20, opacity: 0 }}
                    animate={{ x: 0, opacity: 1 }}
                    transition={{ delay: 0.5 }}
                    className="bg-white rounded-2xl p-8 shadow-sm hover:shadow-lg transition-shadow border border-gray-100"
                >
                     <h3 className="text-xl font-bold text-gray-800 mb-3 flex items-center gap-3">
                        <span className="bg-green-100 text-green-700 py-1 px-3 rounded-lg text-sm font-bold">02</span>
                        {t.multiTitle}
                     </h3>
                     <p className="text-gray-500 leading-relaxed">
                        {t.multiDesc}
                     </p>
                </motion.div>
            </div>

            {/* Disclaimer */}
            <motion.div 
                initial={{ y: 20, opacity: 0 }}
                animate={{ y: 0, opacity: 1 }}
                transition={{ delay: 0.6 }}
                className="bg-red-50 border border-red-100 rounded-2xl p-6"
            >
                <h3 className="text-red-500 font-bold mb-2 uppercase tracking-wide text-sm">
                    {t.disclaimerTitle}
                </h3>
                <p className="text-red-400 text-sm leading-relaxed">
                    {t.disclaimerDesc}
                </p>
            </motion.div>
            
            <div className="mt-12 text-center text-gray-400 text-xs">
                <p>Schisto-Care v1.0 • Powered by Google Gemini</p>
            </div>
        </div>
    </motion.div>
  );
};

export default AboutPage;
