import React from 'react';
import { Language, View } from '../App';
import Footer from './Footer';
import { motion } from 'framer-motion';
import { FileIcon } from './icons';

interface TermsOfServiceProps {
    language: Language;
    onNavigate: (view: View) => void;
}

const TermsOfService: React.FC<TermsOfServiceProps> = ({ language, onNavigate }) => {
    return (
        <motion.div 
            initial={{ opacity: 0 }} 
            animate={{ opacity: 1 }} 
            className="flex flex-col h-full overflow-y-auto bg-[#F8FAFC] text-gray-800"
        >
            <div className="max-w-4xl mx-auto p-8 md:p-12 w-full flex-grow">
                 <div className="flex items-center gap-4 mb-8">
                    <div className="bg-blue-100 p-3 rounded-2xl">
                        <FileIcon className="w-8 h-8 text-blue-600" />
                    </div>
                    <h1 className="text-3xl font-bold text-gray-900">Terms of Service</h1>
                </div>

                <div className="bg-white rounded-3xl p-8 shadow-sm border border-gray-100 space-y-8">
                    <section>
                        <h2 className="text-xl font-bold text-gray-800 mb-3">1. Acceptance of Terms</h2>
                        <p className="text-gray-600 leading-relaxed text-sm">
                            By accessing or using the Schisto-Care Assistant, you agree to be bound by these Terms of Service. If you do not agree, please do not use the app.
                        </p>
                    </section>

                    <section className="bg-red-50 p-6 rounded-2xl border border-red-100">
                        <h2 className="text-xl font-bold text-red-600 mb-3">2. Medical Disclaimer (Important)</h2>
                        <p className="text-gray-700 leading-relaxed text-sm font-medium">
                            Schisto-Care is an informational tool powered by Artificial Intelligence. It is NOT a medical device and does NOT provide medical diagnosis or treatment. The content generated by this app is for educational purposes only. Always seek the advice of your physician or other qualified health provider with any questions you may have regarding a medical condition. Never disregard professional medical advice or delay in seeking it because of something you have read on this app.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold text-gray-800 mb-3">3. User Conduct</h2>
                        <p className="text-gray-600 leading-relaxed text-sm">
                            You agree not to misuse the services. You are solely responsible for your interactions with the AI assistant and the data you choose to share.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold text-gray-800 mb-3">4. Limitation of Liability</h2>
                        <p className="text-gray-600 leading-relaxed text-sm">
                            To the fullest extent permitted by law, Schisto-Care and its developers shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including any loss of profits or revenues, whether incurred directly or indirectly, or any loss of data, use, goodwill, or other intangible losses, resulting from your use of the service.
                        </p>
                    </section>
                </div>
            </div>
            <Footer language={language} onNavigate={onNavigate} />
        </motion.div>
    );
};

export default TermsOfService;
